### ISSUE TITLE
Review of v1.0 milestone

### ISSUE THREAD

**Issue by hsteptoe** [MetOffice/PyPRECIS#16]
Review all content contributing to v1.0 milestone.  For v1.0 this issues avoids making changes to the content - content changes are needed but this is bigger issues to deal with in preparation for v2.0.  

Things to check (in no particular order):

- [x] Does the code run without errors
- [x] Are code comments clear?
- [x] Is the phrasing of questions clear?
- [x] Are all worksheet aims clear?
- [x] Spelling and grammar
- [x] Check code hints are appropriate for code exercises
- [x] Complete answers to code exercises and cross-check answers
- [x] Are there any useful images and links we should add?

Notebooks should be run using **scitools/experimental-current** with python3
